// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.7.1.0
//      SpecFlow Generator Version:1.7.0.0
//      Runtime Version:4.0.30319.235
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
namespace ExampleApp.Spec
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.7.1.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("ChildPage")]
    public partial class ChildPageFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "ChildPivotPage.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "ChildPage", "In order to use ExampleApp\r\nAs a WP7 user\r\nI want to be enter text in the fields " +
                    "on the child pivot page", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
            this.FeatureBackground();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 6
#line 7
 testRunner.Given("my app is uninstalled");
#line 8
 testRunner.Given("my app is installed");
#line 9
 testRunner.Given("my app is not running");
#line 10
 testRunner.Given("my app is running");
#line 11
 testRunner.Then("I wait for \"Waiting...\" to appear");
#line 12
 testRunner.Then("I wait for \"Go!\" to appear");
#line 13
 testRunner.Then("I press the \"Go!\" button");
#line 14
 testRunner.Then("I wait for \"item1\" to appear");
#line hidden
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Pivot Page fields are empty at start")]
        public virtual void PivotPageFieldsAreEmptyAtStart()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Pivot Page fields are empty at start", ((string[])(null)));
#line 16
this.ScenarioSetup(scenarioInfo);
#line 17
 testRunner.Then("I see the \"TextBoxInput\" field contains \"\"");
#line 18
 testRunner.And("I see the \"TextBoxOutput\" field contains \"\"");
#line 19
 testRunner.And("take a picture");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("The Pivot Page output field reverses what I type in input")]
        public virtual void ThePivotPageOutputFieldReversesWhatITypeInInput()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("The Pivot Page output field reverses what I type in input", ((string[])(null)));
#line 21
this.ScenarioSetup(scenarioInfo);
#line 22
 testRunner.Then("I see the \"TextBoxInput\" field contains \"\"");
#line 23
 testRunner.And("I see the \"TextBoxOutput\" field contains \"\"");
#line 24
 testRunner.And("take a picture");
#line 25
 testRunner.Then("I enter \"Hello World\" into \"TextBoxInput\"");
#line 26
 testRunner.Then("I see the \"TextBoxInput\" field contains \"Hello World\"");
#line 27
 testRunner.And("I see the \"TextBoxOutput\" field contains \"dlroW olleH\"");
#line 28
 testRunner.Then("take a picture");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("The Pivot Page has a Pivot which responds to swipes")]
        public virtual void ThePivotPageHasAPivotWhichRespondsToSwipes()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("The Pivot Page has a Pivot which responds to swipes", ((string[])(null)));
#line 30
this.ScenarioSetup(scenarioInfo);
#line 31
 testRunner.Then("I see \"item1\" is left of \"item2\"");
#line 32
 testRunner.And("I see \"item2\" is left of \"item3\"");
#line 33
 testRunner.And("I see \"Input\"");
#line 36
 testRunner.Then("I swipe \"RightToLeft\"");
#line 37
 testRunner.And("I wait 2 seconds");
#line 38
 testRunner.Then("I see \"item2\" is left of \"item3\"");
#line 39
 testRunner.And("I see \"item3\" is left of \"item1\"");
#line 41
 testRunner.And("I see \"You are on pivot 2\"");
#line 43
 testRunner.Then("I swipe \"RightToLeft\"");
#line 44
 testRunner.And("I wait 2 seconds");
#line 45
 testRunner.Then("I see \"item3\" is left of \"item1\"");
#line 46
 testRunner.And("I see \"item1\" is left of \"item2\"");
#line 49
 testRunner.And("I see \"You are on pivot 3\"");
#line 50
 testRunner.Then("I swipe \"LeftToRight\"");
#line 51
 testRunner.And("I wait 2 seconds");
#line 52
 testRunner.Then("I see \"item2\" is left of \"item3\"");
#line 53
 testRunner.And("I see \"item3\" is left of \"item1\"");
#line 55
 testRunner.And("I see \"You are on pivot 2\"");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#endregion
